In [20]:
import torch

x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [21]:
x.requires_grad_(True)              #保存跟踪中间的微分值
x.grad

$$ y=2x^2 = 2 * \begin{bmatrix} 0\\ 1\\ 4\\9\\ \end{bmatrix} = \begin{bmatrix} 28 \end{bmatrix}$$ 


In [22]:
y = 2 * torch.dot(x, x)             
y

tensor(28., grad_fn=<MulBackward0>)

$$ y' = 4x

In [23]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [24]:
x.grad == 4*x

tensor([True, True, True, True])

In [35]:
x.grad.zero_()          #清除之前的的累积梯度
y = x.sum()  
y    


tensor(2., grad_fn=<SumBackward0>)

In [27]:
x = torch.rand(3, requires_grad=True)
y = x**2
z = x + x


In [28]:
x = torch.tensor(1.0, requires_grad=True)
y = torch.tensor(2.0, requires_grad=True)
z = x**2 + y
z.backward()
print(z, x.grad, y.grad)

tensor(3., grad_fn=<AddBackward0>) tensor(2.) tensor(1.)


## **矩阵算梯度转化为标量**  
https://zhuanlan.zhihu.com/p/83172023
<BR> https://www.bilibili.com/video/BV1ZA411H7BU/?spm_id_from=333.337.search-card.all.click&vd_source=da5a4de0e3cf3c81922e2b9dbcbf0372

 $$ z =  x_1 + x_2 + 4 $$

In [30]:
x = torch.ones(2,requires_grad=True)
z = x + 2
z.sum().backward()                
print(x.grad)

tensor([1., 1.])


In [36]:
x = torch.ones(2,requires_grad=True)
z = x + 2
z.backward(torch.ones_like(z)) # grad_tensors需要与输入tensor大小一致
print(x.grad)

tensor([1., 1.])
