In [3]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x+y, x*y, x/y, x**y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [4]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [5]:
x[3]

tensor(3)

In [6]:
len(x)

4

In [7]:
x.shape

torch.Size([4])

In [8]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [9]:
A.T         #A的转置

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

In [10]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])

In [11]:
B==B.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [12]:
X = torch.arange(24).reshape(2, 3, 4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [13]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()
A, A+B, A*B


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

In [14]:
a = 2                                   #张量的每一个元素都会和a相加、相乘
X = torch.arange(24).reshape(2, 3, 4)
a + X, a * X, (a * X).shape 

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]),
 tensor([[[ 0,  2,  4,  6],
          [ 8, 10, 12, 14],
          [16, 18, 20, 22]],
 
         [[24, 26, 28, 30],
          [32, 34, 36, 38],
          [40, 42, 44, 46]]]),
 torch.Size([2, 3, 4]))

In [15]:
x = torch.arange(4, dtype= torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [16]:
A.shape, A.sum()

(torch.Size([5, 4]), tensor(190.))

In [17]:
A_sum_axis0 = A.sum(axis=1)                # axis = 0 把每行都压扁了,组成一个数字，axis = 1 把每列都压扁了，组成一个数字
A_sum_axis0, A_sum_axis0.shape

(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [18]:
A.sum(axis=[0, 1])          #沿着行和列压扁，和sum相同

tensor(190.)

In [19]:
Z = torch.arange(24).reshape(2, 3, 4)
Z, Z.shape

(tensor([[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]],
 
         [[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]),
 torch.Size([2, 3, 4]))

In [20]:
Z_sum_axis0 = Z.sum(axis=0)                 #同理，三维也可以
Z_sum_axis0, Z_sum_axis0.shape

(tensor([[12, 14, 16, 18],
         [20, 22, 24, 26],
         [28, 30, 32, 34]]),
 torch.Size([3, 4]))

In [21]:
Z.sum(axis=[0, 1, 2]) 

tensor(276)

In [22]:
A.mean(), A.sum()

(tensor(9.5000), tensor(190.))

In [23]:
A.numel()           #获取有多少元素

20

In [24]:
A.mean(axis=0)

tensor([ 8.,  9., 10., 11.])

In [25]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [26]:
A.sum(axis=1)

tensor([ 6., 22., 38., 54., 70.])

In [27]:
sum_A=A.sum(axis=1,keepdims=True)        #保持轴数不变，还是纵轴5个
sum_A

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]])

In [28]:
A/sum_A                     #此处是广播，就是会扩展进行相除,A是5*4，sum_A是5*1

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895],
        [0.2222, 0.2407, 0.2593, 0.2778],
        [0.2286, 0.2429, 0.2571, 0.2714]])

In [29]:
A.cumsum(axis=0)            #行的累积总和，不会降维

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [30]:
y = torch.ones(4, dtype = torch.float32)            #点积，x转置乘y
x, y, torch.dot(x, y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [31]:
torch.sum(x * y)

tensor(6.)

In [34]:
A, x, A.shape, x.shape, torch.mv(A, x)        #矩阵向量积, 向量是一列！

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([0., 1., 2., 3.]),
 torch.Size([5, 4]),
 torch.Size([4]),
 tensor([ 14.,  38.,  62.,  86., 110.]))

In [36]:
u = torch.tensor([3.0, -4.0])
torch.norm(u)                   #L2范数

tensor(5.)

In [37]:
torch.abs(u).sum()              #L1范数，就是元素组合

tensor(7.)

In [40]:
a = torch.ones((4, 9))
a, torch.norm(a)                #矩阵范数是矩阵元素平方和的平方根

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor(6.))

练习

In [43]:
A = torch.arange(16, dtype = torch.float32).reshape(4,4)
print(A == A.T.T)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [44]:
B = torch.ones_like(A)              #ones_like和A形状相同的全1的矩阵
print((A.T+B.T)==(A+B).T)

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [45]:
C = torch.randn(4, 4)
print((C+C.T).T == (C+C.T))

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [48]:
D = torch.randn(6, 3, 4)            #len(x为x在横轴上的长度)
len(D)

6

In [50]:
E = torch.arange(24, dtype = torch.float32).reshape(2, 3, 4)
print(E.sum(axis=0).shape)

torch.Size([3, 4])


In [51]:
F = torch.ones(2, 3, 4)
G = torch.ones(2, 3, 4, 5)
print(torch.norm(F))
print(torch.norm(G))

tensor(4.8990)
tensor(10.9545)
