In [2]:
import os

os.makedirs(os.path.join('..','chapter2', 'data'), exist_ok=True)
data_file = os.path.join('..', 'chapter2', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n') 
    f.write('NA,Pave,127500\n')  
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [3]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


In [4]:
inputs, outputs = data.iloc[:, 0:2], data.iloc[:, 2]
inputs = inputs.fillna(inputs.mean())           #用同一列的均值替换“NaN”项,fillna()填补数据集中缺失的项
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [5]:
inputs = pd.get_dummies(inputs, dummy_na=True)      #one-hot编码
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [6]:
import torch

X, y = torch.tensor(inputs.values), torch.tensor(outputs.values)
X, y


(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [13]:
a = data.isnull().sum()         # isnull().sum()找到矩阵中各列为NA的个数
data.drop('Alley', axis=1)
print(a)
print(data)


NumRooms    2
Price       0
dtype: int64
   NumRooms   Price
0       NaN  127500
1       2.0  106000
2       4.0  178100
3       NaN  140000


In [14]:
z = torch.tensor(data.values)
z

tensor([[       nan, 1.2750e+05],
        [2.0000e+00, 1.0600e+05],
        [4.0000e+00, 1.7810e+05],
        [       nan, 1.4000e+05]], dtype=torch.float64)